--liquibase formatted sql

CREATE TABLE if not exists dog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR,
    breed         VARCHAR,
    year_of_birth INTEGER,
    description   VARCHAR
);

CREATE TABLE if not exists cat
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR,
    breed         VARCHAR,
    year_of_birth INTEGER,
    description   VARCHAR
);

CREATE TABLE if not exists catUsers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR,
    year_of_birth INTEGER,
    info          VARCHAR,
    email         VARCHAR,
    chat_id       BIGINT,
    cat_id        BIGINT REFERENCES cat (id),
    status        VARCHAR
);

CREATE TABLE if not exists dogUsers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR,
    year_of_birth INTEGER,
    info          VARCHAR,
    email         VARCHAR,
    chat_id       BIGINT,
    dog_id        BIGINT REFERENCES dog (id),
    status        VARCHAR
);

CREATE TABLE if not exists contexts
(
    chat_id      BIGSERIAL PRIMARY KEY,
    shelter      VARCHAR,
    cat_owner_id BIGINT REFERENCES catUsers (id),
    dog_owner_id BIGINT REFERENCES dogUsers (id)
);


CREATE TABLE if not exists cat_report
(
    id          BIGINT generated by default as identity primary key,
    chat_id     bigint NOT NULL,
    text_report TEXT,
    file_id     TEXT,
    date        DATE   NOT NULL
);

CREATE TABLE if not exists dog_report
(
    id          BIGINT generated by default as identity primary key,
    chat_id     bigint NOT NULL,
    text_report TEXT,
    file_id     TEXT,
    date        DATE   NOT NULL
);